[package]
name = "control-structures"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
# tokio = "1.16.1"
# thirtyfour = "0.28.2"
